name: detection-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0
  - torchvision
  - cudatoolkit=11.8  # Match your GPU
  - paho-mqtt
  - opencv
  - diffusers
  - transformers  # For optional image gen
  - gtts  # TTS
  - mlflow
  - pip:
    - requests
